sudo : false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
  - npm install --production
script:
  - npm run test
  - npm run code-coverage
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
